spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_spring
    username: vuespring
    password: vuespring
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 15MB
      resolve-lazily: true

  session:
    timeout: 1800

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
  type-aliases-package: com.study.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


file:
  upload-folder: C:/Temp/upload/
  allowed-extensions: jpg,png,gif,zip

jwt:
  secret-key: kjs
#  access-token-expiration: 1800000 # 30분
  access-token-expiration: 604800000 # 30분
  refresh-token-expiration: 604800000 #7일